dist: trusty
sudo: required

language: node_js
node_js:
  - "8"

addons:
  - chrome: stable

cache:
  directories:
     - ./node_modules

install:
  - npm install

script:
  - npm run missing-translations
  - npm run lint  --bailOnLintError true
  - npm test
  - npm run test:e2e
  - npm run build -- --prod
